### ISSUE TITLE
NameError: name 'logging' is not defined

### ISSUE THREAD

**Issue by futureflsl** [fossfreedom/indicator-sysmonitor#101]
ubuntu18.04
Traceback (most recent call last):
  File "/usr/lib/indicator-sysmonitor/preferences.py", line 344, in on_save
    self.update_autostart()
  File "/usr/lib/indicator-sysmonitor/preferences.py", line 403, in update_autostart
    logging.exception(ex)
NameError: name 'logging' is not defined

**Comment by fossfreedom** [comment]
You either have a permissions issue that prevents preferences.json being read or written to - or the file itself is corrupt file.  Please check

    .cache/indicator-sysmonitor/preferences.json
