### ISSUE TITLE
Python dependency related error with psutil

### ISSUE THREAD

**Issue by GiantEnemyCrab** [fossfreedom/indicator-sysmonitor#106]
My enivonrment:
- Debian 11 Bullseye (currently in test as of 8/10/2021, but set to release as stable on 8/14/2021)
- I used `sudo make installbudgie` followed by `budgie-panel --replace &`
- I then tried to add the applet, then I see an error from the terminal as:
```
** (budgie-panel:2311): WARNING **: 18:11:10.395: Error importing plugin 'budgiesysmonitor':
Traceback (most recent call last):
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/budgie-desktop/plugins/budgiesysmonitor/budgiesysmonitor.py", line 26, in <module>
    from preferences import Preferences
  File "/usr/lib/budgie-desktop/plugins/budgiesysmonitor/preferences.py", line 21, in <module>
    from sensors import SensorManager
  File "/usr/lib/budgie-desktop/plugins/budgiesysmonitor/sensors.py", line 25, in <module>
    import psutil as ps
ModuleNotFoundError: No module named 'psutil
```

I worked around this issue by doing `sudo apt install python3-pip` followed by `sudo pip install psutil`, then this worked fine.
But I feel users don't have to manually do `pip install` command. Is there something that could be done?

**Comment by fossfreedom** [comment]
The package is available in bullseye

    sudo apt install python3-psutil

**Comment by GiantEnemyCrab** [comment]
Thank you very much for the quick response, and I realize that you had documented this, too.
Will close this.

**Comment by GiantEnemyCrab** [comment]
A side question @fossfreedom, I find this very useful and wondered if this become available as a `apt` installable debian package someday?
