### ISSUE TITLE
sudently can not work

### ISSUE THREAD

**Issue by mannfuri** [fossfreedom/indicator-sysmonitor#127]
```
Jul 21 22:07:52 mypc systemd[972]: Started Application launched by gnome-shell.
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: INFO:root:start
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: INFO:root:Menu shown
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: INFO:root:Fetcher started
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: ERROR:root:Error running: True
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: Exception in thread Thread-1:
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: Traceback (most recent call last):
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     self.run()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 718, in run
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: ERROR:root:Error running: True
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     data = self.fetch()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 712, in fetch
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     return self.mgr.get_results()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 287, in get_results
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     res[sensor] = BaseSensor.script_exec(self.settings["sensors"][sensor][1])
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 337, in script_exec
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     return output.decode('utf-8') if output else _("(no output)")
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: Traceback (most recent call last):
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/bin/indicator-sysmonitor", line 266, in <module>
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     app = IndicatorSysmonitor()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/bin/indicator-sysmonitor", line 101, in __init__
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     self.load_settings()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/bin/indicator-sysmonitor", line 174, in load_settings
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     self.update_indicator_guide()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/bin/indicator-sysmonitor", line 135, in update_indicator_guide
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     guide = self.sensor_mgr.get_guide()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 206, in get_guide
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     data = self._fetcher.fetch()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 712, in fetch
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     return self.mgr.get_results()
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 287, in get_results
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     res[sensor] = BaseSensor.script_exec(self.settings["sensors"][sensor][1])
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:   File "/usr/lib/indicator-sysmonitor/sensors.py", line 337, in script_exec
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]:     return output.decode('utf-8') if output else _("(no output)")
Jul 21 22:07:53 mypc indicator-sysmonitor.desktop[4730]: AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

this is what i get from /var/log/syslog
i using ubuntu 22.10
make some change,then work it out.
and this is what i did.

![图片](https://github.com/fossfreedom/indicator-sysmonitor/assets/91338215/9c7443c2-7bc1-455d-b6fb-b01dfaa6b07c)

**Comment by fossfreedom** [comment]
no real detail here how to reproduce
