### ISSUE TITLE
indicator-sysmonitor doesnt work with kernel liquorix

### ISSUE THREAD

**Issue by skypce** [fossfreedom/indicator-sysmonitor#28]
Hi, i have problems between liquorix kernel and indicator:
 please see the report:
4.0-5.dmz.3-liquorix-amd64 #1 ZEN SMP PREEMPT Debian 4.0-12 (2015-06-14) x86_64 x86_64 x86_64 GNU/Linux
i am running ubuntu 15.04 this is the error:
Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 230, in <module>
    app = IndicatorSysmonitor()
  File "/usr/bin/indicator-sysmonitor", line 101, in __init__
    self.load_settings()
  File "/usr/bin/indicator-sysmonitor", line 150, in load_settings
    self.update_indicator_guide()
  File "/usr/bin/indicator-sysmonitor", line 135, in update_indicator_guide
    guide = self.sensor_mgr.get_guide()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 198, in get_guide
    data = self._fetcher.fetch()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 564, in fetch
    return self.mgr.get_results()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 272, in get_results
    value = instance.get_value(sensor)
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 377, in get_value
    return '{:02.0f}%'.format(self._fetch_mem())
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 385, in _fetch_mem
    minor_version = int(release[1])
ValueError: invalid literal for int() with base 10: '0-5'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 570, in run
    data = self.fetch()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 564, in fetch
    return self.mgr.get_results()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 272, in get_results
    value = instance.get_value(sensor)
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 377, in get_value
    return '{:02.0f}%'.format(self._fetch_mem())
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 385, in _fetch_mem
    minor_version = int(release[1])
ValueError: invalid literal for int() with base 10: '0-5'

I really appreciate if you fix this problem, i love liquorix kernel and the indicator-sysmonitor. Thank you in advance.

**Comment by fossfreedom** [comment]
@skypce 

 think the above commit fixes this.  Please give this a try and let me know.

Thanks

**Comment by skypce** [comment]
Hello , yes, now it working fine, very thank you.
