### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by er3456qi** [fossfreedom/indicator-sysmonitor#66]
$ indicator-sysmonitor
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 20, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found

**Comment by er3456qi** [comment]
I have fixed this issue by install gir1.2-appindicator3-0.1.

sudo apt install gir1.2-appindicator3-0.1

**Comment by fossfreedom** [comment]
cheers - have updated the README with your recommendation
